---
vagrantfile-local:
    vm:
        box: Zalesiai (Debian Wheezy 7.2 x64)
        box_url: 'http://box.puphpet.com/debian-wheezy72-x64-vbox43.box'
        hostname: null
        network:
            private_network: 192.168.42.101
            forwarded_port: {  }
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: 768
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: .vagrant/puppet
                manifest_file: manifest.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/.vagrant/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder: {  }
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - acl
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
apache:
    modules:
        - php
        - rewrite
    vhosts:
        KHYEVrxEKLmQ:
            servername: sylius.dev
            serveraliases:
                - www.sylius.dev
            docroot: /var/www/web
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
    user: www-data
    group: www-data
    default_vhost: true
    mpm_module: prefork
    mod_pagespeed: 0
    mod_spdy: 0
php:
    version: '54'
    composer: '1'
    modules:
        php:
            - cli
            - curl
            - gd
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
            - apc
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: Europe/Vilnius
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
        xdebug.max_nesting_level: '1000'
xhprof:
    install: '1'
mysql:
    root_password: '123'
    phpmyadmin: 0
    adminer: 0
    databases:
        ECH7iHHuaxpE:
            grant:
                - ALL
            name: zalesiai
            host: localhost
            user: zalesiai
            password: zalesiai
            sql_file: ''
